== Execution

This chapter explains how to execute GraphQL queries using GQL.

=== Executor

==== From a schema

In order to execute any GraphQL query first you need to get an instance of an `GraphQLExecutor`

[source, groovy]
----
import gql.DSL

include::{testMain}/gql/DSLSpec.groovy[tags=executor, indent=0]
----

Once you have an executor you can reuse it to execute as many queries as you like without incurring in
performance issues.

[source, groovy]
----
def result1 = executor.execute query1
def result2 = executor.execute query2
...
----

[sidebar]
.Direct execution deprecation
****
From version 0.4.0 direct execution of queries is deprecated in favor of reusing executor instances.
That improves a lot GraphQL queries execution performance.

Therefore calls like the following one are marked as deprecated and will be removed in the future:

[source, groovy]
----
include::{testMain}/gql/DSLSpec.groovy[tags=executeQueryStringNoArguments, indent=0]
----
<1> Executing directly the query
<2> Getting data if no errors happened
<3> Getting errors in case of something went wrong
****

==== With options

You can also create an instance of `GraphQLExecutor` initializing some execution options like GraphQL instrumentations:

[source, groovy]
----
include::{testMain}/gql/DSLSpec.groovy[tags=executorWithInstrumentation, indent=0]
----

=== Simple query execution

Once you've got an instance of `GraphQLExecutor` you can execute a query:

[source, groovy]
----
import gql.DSL

include::{testMain}/gql/DSLSpec.groovy[tags=executorExample, indent=0]
----
<1> Creating an instance of `GraphQLExecutor`
<2> The result of executing a query is a `graphql.ExecutionResult`
<3> The result could contain some data
<4> Or could contain GraphQL errors

[sidebar]
.ExecutionResult#getData()
****
ExecutionResult `getData()` method has the following signature

[source, groovy]
----
<T> T getData()
----

Which means that, in a variable declaration, the right operand will be automatically casted to the type of the
left operand. This is useful if you want to use static compilation, but also dangerous if you're not sure of the type
data is going to return.

****

=== Passing arguments

In order to execute a given query with arguments you can use `GraphQLExecutor#execute(string, variables)`:

[source, groovy]
.query
----
include::{testMain}/gql/DSLSpec.groovy[tags=queryWithArguments, indent=0]
----

[source, groovy]
.execution
----
include::{testMain}/gql/DSLSpec.groovy[tags=queryWithArgumentsExecution, indent=0]
----

=== Async Execution

GQL through `graphql-java` can use fully asynchronous execution when
executing queries. You can get a
`java.util.concurrent.CompleteableFuture` of an `ExecutionResult` by
calling `GraphQLExecutor#executeAsync()` like this:

[source, groovy]
.async
----
include::{testMain}/gql/dsl/executor/GraphQLExecutorSpec.groovy[tags=newExecutorExecuteAsync, indent=0]
----

If a data fetcher returns a CompletableFuture<T> object then this will
be composed into the overall asynchronous query execution. This means
you can fire off a number of field fetching requests in
parallel. Exactly what threading strategy you use is up to your data
fetcher code.

=== Query builders

**GQL** allows you to execute queries directly or to build them to use them later via DSL
builder. The former is useful if you already have the queries and you
are sure they work as expected. The latter is a safer way of building
queries because it gives you some sanity checks based on the types
used.

==== Execute queries

If you're using the underlying **GQL** GraphQL engine to execute your queries, it would be nice
to be able to declare and execute queries in one shot right ?

[source, groovy]
----
import gql.DSL
include::{testMain}/gql/DSLSpec.groovy[tags=importExecutionResult, indent=0]
include::{testMain}/gql/DSLSpec.groovy[tags=staticQueryChecked, indent=0]
----

<1> Defines a `query` with name `byYear` mapping query parameters
<2> Checks that the fields used in the close are present in type `Film`. Uses static check to make sure fields are
present in type `Film`
<3> Defines a given alias to the query result

[source, groovy]
----
import gql.DSL
include::{testMain}/gql/DSLSpec.groovy[tags=importExecutionResult, indent=0]
include::{testMain}/gql/DSLSpec.groovy[tags=staticQueryUnchecked, indent=0]
----

<1> Defines a `query` with name `lastFilm` mapping variables
<2> Declares a set of fields but are not checked
<3> Defines a given alias to the query result

[sidebar]
.Executing mutations directly ?
****
At the moment, in order to execute a mutation you have to create the mutation string first
using `DSL.buildMutation` and then use `GraphQLExecutor#execute` to execute the mutation against the
schema. Check the `Mutation string` section.
****

==== Query string

Sometimes your exposed GraphQL schema may be backed up by another third party GraphQL engine implementation, but
instead of writing or queries by hand we still may want to use the DSL to build the query and then use the resulting
string against the other engine.

[source, groovy]
----
import gql.DSL

include::{testMain}/gql/DSLSpec.groovy[tags=queryString, indent=0]
----

==== Nested queries

From version 1.1.0 you can create nested queries:

[source, groovy]
.Nested queries
----
import gql.DSL

include::{testMain}/gql/dsl/QueryBuilderSpec.groovy[tags=nestedQueries, indent=0]
----

==== Mutation string

Of course apart from queries you may want to execute mutations.

[source, groovy]
.Mutation strings
----
import gql.DSL

include::{testMain}/gql/dsl/MutationBuilderSpec.groovy[tags=simple_mutation, indent=0]
----

Nesting also works for mutations:

[source, groovy]
.Nested queries in mutations
----
import gql.DSL

include::{testMain}/gql/dsl/MutationBuilderSpec.groovy[tags=nestedQueries, indent=0]
----

=== Exposing GraphQL

==== From GraphQLExecutor

From any `gql.dsl.executor.GraphQLExecutor` you can get the underlying `graphql.GraphQL` instance:

[source, groovy]
.Accessing underlying GraphQL instance
----
include::{testMain}/gql/dsl/executor/GraphQLExecutorSpec.groovy[tags=newExecutorGraphQL, indent=0]
----

==== Directly from DSL

Because GQL can't think on every single case, there's a chance somebody may miss to access to the `graphql-java`
low level API.

[source, groovy]
.Low level GraphQL
----
include::{testMain}/gql/DSLSpec.groovy[tags=newGraphQLBuilderSchema, indent=0]
----

Or if you'd like to initialize it with some options:

[source, groovy]
.Low level GraphQL (Options)
----
include::{testMain}/gql/DSLSpec.groovy[tags=newGraphQLBuilderOptions, indent=0]
----
