== Intro

**GQL** is a set of Groovy DSLs and AST transformations built on top of
https://github.com/graphql-java/graphql-java[GraphQL-java] to make it easier building GraphQL schemas and
execute **GraphQL** queries without losing type safety.

**GraphQL** is a query language. It's based in a type system and defines a specific query language
and how a specific query engine should work in order to process and execute GraphQL queries.

IMPORTANT: For a full detailed explanation about GraphQL I would recommend you to take
a look at the official tutorial at http://graphql.org/learn/

Keeping long story short When dealing with **GraphQL** you normally will be following the these steps:

- **Define the schema** (first types, scalars...and then adding those types to schema roots)
- **Expose the schema** (via the chosen GraphQL implementation engine)
- **Execute queries** against the implementation engine

[ditaa]
....

 +---------+ enables +-----------+ enables +---------+ enables +---------+
 |  define +-------->| add types +-------->| expose  +-------->| execute |
 |  types  |         | to schema |         | schema  |         | queries |
 +---------+         +-----------+         +---------+         +---------+

....

Some of the ideas behind **GQL**:

- It should be **IDE friendly**
- It should be built having **static compilation** in mind
- It should **not need more than one import**
