=== Queries

==== Execution

===== Withouth arguments

In order to execute a given query string you can use `DSL.execute(schema, string)`. Given a query:

[source, groovy]
.query
----
include::{testMain}/gql/DSLSpec.groovy[tags=executeQueryStringNoArgumentsQuery, indent=0]
----

You can execute it against a given schema as follows:

[source, groovy]
----
import gql.DSL

include::{testMain}/gql/DSLSpec.groovy[tags=executeQueryStringNoArguments, indent=0]
----
<1> The result of executing a query is a `graphql.ExecutionResult`
<2> The result could contain some data
<3> Or could contain GraphQL errors

[sidebar]
.ExecutionResult#getData()
****
ExecutionResult `getData()` method has the following signature

[source, groovy]
----
<T> T getData()
----

Which means that, in a variable declaration, the right operand will be automatically casted to the type of the
left operand. This is useful if you want to use static compilation, but also dangerous if you're not sure of the type
data is going to return.

****

===== With arguments

In order to execute a given query with arguments you can use `DSL.execute(schema, string, variables)`:

[source, groovy]
.query
----
include::{testMain}/gql/DSLSpec.groovy[tags=queryWithArguments, indent=0]
----

[source, groovy]
.execution
----
include::{testMain}/gql/DSLSpec.groovy[tags=queryWithArgumentsExecution, indent=0]
----

==== Query builders

**GQL** allows you to execute queries directly or to build them to use them later via DSL
builder. The former is useful if you already have the queries and you
are sure they work as expected. The latter is a safer way of building
queries because it gives you some sanity checks based on the types
used.

===== Execute queries

If you're using the underlying **GQL** GraphQL engine to execute your queries, it would be nice
to be able to declare and execute queries in one shot right ?

[source, groovy]
----
import gql.DSL
include::{testMain}/gql/DSLSpec.groovy[tags=importExecutionResult, indent=0]
include::{testMain}/gql/DSLSpec.groovy[tags=staticQueryChecked, indent=0]
----

<1> Defines a `query` with name `byYear` mapping query parameters
<2> Checks that the fields used in the close are present in type `Film`. Uses static check to make sure fields are
present in type `Film`
<3> Defines a given alias to the query result

[source, groovy]
----
import gql.DSL
include::{testMain}/gql/DSLSpec.groovy[tags=importExecutionResult, indent=0]
include::{testMain}/gql/DSLSpec.groovy[tags=staticQueryUnchecked, indent=0]
----

<1> Defines a `query` with name `lastFilm` mapping variables
<2> Declares a set of fields but are not checked
<3> Defines a given alias to the query result

===== Query string

Sometimes your exposed GraphQL schema may be backed up by another third party GraphQL engine implementation, but
instead of writing or queries by hand we still may want to use the DSL to build the query and then use the resulting
string against the other engine.

[source, groovy]
----
import gql.DSL

include::{testMain}/gql/DSLSpec.groovy[tags=queryString, indent=0]
----
