=== Node

A **Node** is a type that can be retrieved by an unique identifier. Therefore a node always has an **id** field.

Apart from the **id** field, a node can have more fields. However there's a special type of node field
called **connection**. A **Connection** is a type of fields mapping one-to-many relationships.
Here's an example on how to declare a new node:

[source, groovy]
.Simple Node
----
include::{testMain}/gql/relay/RelaySpec.groovy[tags=simpleNode, indent=0]
----

<1> Node description
<2> Fields

NOTE: You don't have to declare the **id** field. **GQL** has already added for you every
time you declare a node type.

Although you can always declare a connection as a normal field and build the connection type via the `DSL.connection()`
method, you can do it directly in the DSL like this:

[source, groovy]
.Node with embedded connection
----
include::{testMain}/gql/relay/RelaySpec.groovy[tags=nodeWithListFetcher, indent=0]
----

<1> Declaring a normal field
<2> Declaring a connection with connection edges' nodes of type `Ship`
<3> Declaring a special fetcher to get the result

==== listFetcher

To fetch the content of a **connection** field you can always use a simple data fetcher, but because a **Connection**
field has always some repetitive meta data, GQL has abstracted the way that metadata is created.

All you have to do is to make the `listFetcher { }` invocation to return a list of the edge items, then GQL will took
over and it will fulfill the information relative to `pageInfo` and `edges`.
