== Getting started

=== Hello GQL

This is how a full GraphQL life cycle app looks like using **GQL**:

[source, groovy]
----
@Grab('com.github.grooviter:gql-core:0.2.0')
include::{baseDirFirstLevel}/gql-core/src/test/groovy/gql/DSLSpec.groovy[tags=grabExample, indent=0]
----

<1> Creates a type `GraphQLFilm`
<2> Creates a `GraphQL schema` using the previously defined types
<3> Executes a `GraphQL query string` against the schema

NOTE: You can execute the example as a Groovy script in the command line or using
the http://www.groovy-lang.org/groovyconsole.html[Groovy console] both available in
any Groovy distribution.

NOTE: We have executed the query as a query string, however there is
a safer way of building queries using the `DSL.query()`` builder. It gives you some sanity checks based on the types
used.

=== Gradle

You can add the following dependency to your Gradle project

[source, gradle, subs="attributes"]
----
compile 'com.github.grooviter:gql-core:{releaseVersion}'
----

The library is available at Bintray so all you have to do is
to include the `jcenter()` declaration in your dependency repositories
in your Gradle script.

[source, groovy]
----
repositories {
   jcenter()
}
----
