=== Inputs

Apart from using scalar values, like enums or string when passing arguments to a given query
you can also easily pass complex objects. This is particularly valuable in the case of mutations, where
you might want to pass in a whole object to be created. In GraphQL that means using input types.

Lets say we have a query to filter our mail inbox by `from` and `to`:

[source, groovy]
.query
----
include::{testMain}/gql/dsl/InputTypeSpec.groovy[tags=inputTypeQuery, indent=0]
----

We can model the `MailFilter` input type as:

[source, groovy]
.declaration
----
include::{testMain}/gql/dsl/InputTypeSpec.groovy[tags=inputTypeDeclaration, indent=0]
----

And finally when executing the query we can pass a map with the mail filter values.

[source, groovy]
.execution
----
include::{testMain}/gql/dsl/InputTypeSpec.groovy[tags=inputTypeQueryExecution, indent=0]
----

==== Arguments

Input types can only be used as an argument of a `query` or a `mutation`. Therefore when
declaring a given mutation, you can say that the argument of that `query` or `mutation`
can be of input type `X`:

[source, groovy]
.arguments
----
include::{testMain}/gql/dsl/InputTypeSpec.groovy[tags=inputTypeArgument, indent=0]
----

[sidebar]
.Why there is no `type` method inside `argument` ?
****
In previous versions there was the possibility of doing:

[source, groovy]
----
field('name') {
   type outputType // --> output
   argument('argumentName') {
     type inputType // --> input? output?
     description 'description'
   }
}
----

But that led to ambiguity, specially because the user could think any type could be used
as an argument. That's why it's been removed, and even the upper `type` method is not visible
inside the `argument` scope
****
