=== Modularising

Modularising the way you create GraphQL schemas has at least a couple of benefits:

- **Enables you to write using plain GraphQL language**: Writing code is cool, but you may be used to writing GraphQL schemas
using the GraphQL language directly.
- **It allows you to separate parts of the schema by areas of interest**: No more a huge single file declaring
everything in one place

Lets say we have three different schema files in our classpath, and we would like to merge them all in order to
create a sigle schema:

[source, groovy]
.films
----
include::{testResources}/gql/dsl/films.graphqls[indent=0]
----

[source, groovy]
.bands
----
include::{testResources}/gql/dsl/bands.graphqls[indent=0]
----

[source, groovy]
.qandm.graphqls
----
include::{testResources}/gql/dsl/qandm.graphqls[indent=0]
----

In this first example we will be using `java.util.URI` instances to locate our files, but as we will see later,
we can just use a `java.lang.String` to indicate where those files are within the application class loader.

[source, groovy]
.as URIs
----
include::{testMain}/gql/dsl/SchemaMergerBuilderSpec.groovy[tags=uris, indent=0]
----

Then you can merge all of them. In this example we'll only be mapping the query fields with the data fetchers
needed to return some response.

[source, groovy]
.as URIs
----
import gql.DSL

include::{testMain}/gql/dsl/SchemaMergerBuilderSpec.groovy[tags=urisSchema, indent=0]
----

<1> Merging schema fragment (only type definitions)
<2> Merging another schema fragment but, this time, mapping inner types to some data fetchers
<3> Declaring the interest to map some of the fields of type `QueryType`
<4> Mapping a given data fetcher to field `randomField`

And using just strings to indicate where the files are in the classpath:

[source, groovy]
.as URIs
----
import gql.DSL

include::{testMain}/gql/dsl/SchemaMergerBuilderSpec.groovy[tags=resourcesSchema, indent=0]
----

==== Custom Scalar implementation

If you'd like to add a custom scalar implementation when using the
modularization mechanism, you can do it from version
`0.1.9-alpha`. All you have to do is:

Declare the scalar in the schema:

[source, groovy]
.IDL
----
include::{testResources}/gql/dsl/bands.graphqls[indent=0]
----

Then create the scalar implementation with the Groovy DSL:

[source, groovy]
.Custom scalar
----
include::{testMain}/gql/dsl/SchemaMergerBuilderSpec.groovy[tags=customScalar, indent=0]
----

And finally add the reference to the `DSL.mergeSchemas` body:

[source, groovy]
.Schema
----
include::{testMain}/gql/dsl/SchemaMergerBuilderSpec.groovy[tags=mergeSchemasWithCustomScalar, indent=0]
----

==== Type resolvers

IMPORTANT: If you're using any of the GraphQL types that require a type resolver and you forgot to
add it to the DSL, you will get a runtime exception.

===== Interfaces

At some point you may want to create an interface as a base for other types.

[source, groovy]
.Schema
----
include::{testResources}/gql/dsl/Interfaces.graphqls[indent=0]
----

When using interfaces you need to provide a type resolver to make the GraphQL engine
capable to decide when to return one type or another depending on the object return
by the data fetcher.


[source, groovy]
.Type resolver usage
----
include::{testMain}/gql/dsl/SchemaMergerBuilderSpec.groovy[tags=typeResolver, indent=0]
----

<1> The data fetcher returns a list of maps
<2> Declaring a type resolver for type `Raffle`
<3> The type resolver holds a reference of every item
<4> The type resolver decides it is a TwitterRaffle if the map has a key `hashTag` otherwise it will be considered a `SimpleRaffle`
<5> The query wants to get the information of a `TwitterRaffle`

The `typeResolver` method could receive both a `graphql.schema.TypeResolver` instance or a `Closure`
keeping the contract of the `TypeResolver` functional interface like the example above.

===== Union Types

For union types the mechanism is the same. You only have to add a type resolver to
the union type. Lets say we have the following schema:

[source, groovy]
.Schema
----
include::{testResources}/gql/dsl/UnionTypes.graphqls[indent=0]
----

There are both interfaces and union types, but the way we add a type resolver to
any of them is just the same:

[source, groovy]
.Type resolver usage
----
include::{testMain}/gql/dsl/SchemaMergerBuilderSpec.groovy[tags=typeResolverToUnionSchema, indent=0]
----

Then you can apply a query like the following:

[source, groovy]
.Type resolver usage
----
include::{testMain}/gql/dsl/SchemaMergerBuilderSpec.groovy[tags=typeResolverToUnionQuery, indent=0]
----
