=== Types

Types define the structure of the data you want to expose. There two main sets of types, scalars and custom types. The
former are specified by the GraphQL specification and are basic types such as strings, integers...etc whereas the latter
refer to the types the developer will be defining (a Book, a Car...etc). We'll make use of the scalars to build our
own types.

==== Full types

In order to define a full type using **GQL** the only thing you have to do is to import **gql.DSL** and use the method
`type`:

[source, groovy]
----
import gql.DSL

include::{testMain2}/gql/DSLSpec.groovy[tags=fullType, indent=0]
----

<1> Defines a new type called `Film`
<2> Adds a type description (useful to client users when exposing the schema)
<2> Adds a field of type string (GraphQLString)

NOTE: The resulting `type` variable is an instance of `graphql.schema.GraphQLObjectType`.
We haven't added the specific type to highlight the fact that no other import is needed. All basic scalar types such
as `GraphQLString` are defined within the DSL and both the compiler and the IDE should be able to recognize them.

You can add as many `field('fieldName') { }` blocks to your type as you want.

==== Shorter field definition

There is a shorter way of defining a given type. It's specially useful when you're prototyping or when you don't care
about adding descriptions to your types. You can use the method `field(String, Scalar)` method within the `type` DSL.
The following example adds three different fields to the `Droid` type:

[source, groovy]
----
import gql.DSL
include::{testMain2}/gql/DSLSpec.groovy[tags=importGraphQLObjectType, indent=0]

include::{testMain2}/gql/DSLSpec.groovy[tags=shortest, indent=0]
----

==== Adding external fields

Sometimes you may want to keep type and field definitions apart, maybe to reuse those definitions, or maybe because it
gives you more flexibility when structuring your app.

In the following example a field called name. It will always return its value in uppercase.

[source, groovy]
----
import gql.DSL

include::{testMain2}/gql/DSLSpec.groovy[tags=standaloneFieldDefinition, indent=0]
----

[sidebar]
.Static compilation
****
If you would like to use static compilation here, I think is important to bear in mind **getSource()** signature:

[source, groovy]
----
<T> T getSource()
----

This signature means that the result of executing **getSource()** will be casted to the element type found on
the left hand side.

[source, groovy]
----
import gql.DSL

include::{testMain2}/gql/DSLSpec.groovy[tags=fieldStaticCompilation, indent=0]
----

<1> **DataFetchingEnvironment#getSource()** casts its result to the left side element
type (Map<String,Integer> in this case)
<2> Then the compiler is ok with substracting 1 from an integer

****

Then we can use this definition in any type we want usign the `addField` method inside `type` DSL. In the example
every person's name will be returned in uppercase.

[source, groovy]
----
import gql.DSL

include::{testMain2}/gql/DSLSpec.groovy[tags=addField, indent=0]
----




