name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    env:
      ORG_GRADLE_PROJECT_PUBLISH_SIGN_KEY_ID: ${{ secrets.ORG_GRADLE_PROJECT_PUBLISH_SIGN_KEY_ID }}
      ORG_GRADLE_PROJECT_PUBLISH_SIGN_KEY: ${{ secrets.ORG_GRADLE_PROJECT_PUBLISH_SIGN_KEY }}
      ORG_GRADLE_PROJECT_PUBLISH_SIGN_SECRET: ${{ secrets.ORG_GRADLE_PROJECT_PUBLISH_SIGN_SECRET }}
      ORG_GRADLE_PROJECT_PUBLISH_REPO_USERNAME: ${{ secrets.ORG_GRADLE_PROJECT_PUBLISH_REPO_USERNAME }}
      ORG_GRADLE_PROJECT_PUBLISH_REPO_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_PUBLISH_REPO_PASSWORD }}
      ORG_GRADLE_PROJECT_PUBLISH_GH_TOKEN: ${{ secrets.ORG_GRADLE_PROJECT_PUBLISH_GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
      - name: release
        run: ./gradlew build release -x aggregateCodenarc -x aggregateGroovydoc
