name: master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: build
        run: ./gradlew build
      - name: release
        env:
          PUBLISH_SIGN_ENABLED: true
          PUBLISH_SIGN_KEY_ID: ${{ secrets.PUBLISH_SIGN_KEY_ID }}
          PUBLISH_SIGN_KEY: ${{ secrets.PUBLISH_SIGN_KEY }}
          PUBLISH_SIGN_SECRET: ${{ secrets.SIGN_SECRET }}
          PUBLISH_REPO_USERNAME: ${{ secrets.PUBLISH_REPO_USERNAME }}
          PUBLISH_REPO_PASSWORD: ${{ secrets.PUBLISH_REPO_PASSWORD }}
          PUBLISH_GH_TOKEN: ${{ secrets.PUBLISH_GH_TOKEN }}
        run: ./gradlew clean build release
